layout = "layouts/main.njk"
language = "ja"

[info]
title = "Think"
author = "Asuka"
create_year = 2018
repository = "https://github.com/a-skua/a-skua.github.io"

[[nav.contents]]
title = "Home"
url = "/"

[[nav.contents]]
title = "About"
url = "/about/"

[[nav.contents]]
title = "Blog"
url = "/blog/"
